### PR TITLE
Assign unique identifier to channel 

### PR DESCRIPTION
**Pull request by ahbou**
Channels are referenced by their unique identifier when available.
This allows to subscribe to multiple channels and broadcast to specific ones.

### CODE REVIEW

**Comment by danielrhodes** [comment]
Thanks @ahbou! Taking a look at this soon.

**Comment by novall** [comment]
Hi @danielrhodes @ahbou! What is the status on this PR? I can try to point to this branch in my podfile but wanted to see if everything checks out / conflicts are resolved. I just need to be able to subscribe to multiple channels at once. Thanks for your help!

**Comment by ahbou** [comment]
Hi @novall I've been using it since then with no issues.
I also updated it to support Swift 4 and the latest Starscream. (hence the conflicts)
You can point to my fork [ahbou/Swift-ActionCableClient](https://github.com/ahbou/Swift-ActionCableClient/)  to try it out

**Comment by novall** [comment]
Thank you @ahbou! This worked great!! 😊

**Comment by allaire** [comment]
This created a regression for us on iOS 10.X, I'm still investigating.

For some reason I can't figure out, for one of our channel, I need to pass the channel name as the first item in the identifier dictionnary: `identifier: ["channel": "ConversationsChannel", "member_id": member.id]` to make it works on iOS 10. No idea what's going on.

**Comment by allaire** [comment]
I found the issue, the code is broken because it's always relying on the first element of the identifier dictionnary. The issue happens when the order is different in the `JSONSerializer.deserialize` method. We had a regression in iOS 10 only because the order of the JSON is different than iOS 11. See below:

```
iOS 11

{"identifier":"{\"member_id\":\"20c5edcc-5dda-4f43-a0df-b86a908001b6\",\"channel\":\"ConversationsChannel\"}","type":"confirm_subscription"}

iOS 10

{"identifier":"{\"channel\":\"ConversationsChannel\",\"member_id\":\"20c5edcc-5dda-4f43-a0df-b86a908001b6\"}","type":"confirm_subscription"}
```

This cause a problem because the channel's key in `unconfirmedChannels` is the member's uuid (since it's always the first element of the identifier dictionnary in the `create` method, but the message.uid is `ConversationsChannel` under iOS 10 because that's the first element of the onText `text` JSON.

A quick fix would be to remove the `channel` key, but I think the solution is not really elegant to be honest. We could also create a unique hash using a similar technique like this one: 
https://github.com/rails/rails/blob/master/actioncable/app/assets/javascripts/action_cable/subscription.coffee#L54

cc @ahbou @danielrhodes

**Comment by allaire** [comment]
Opened https://github.com/danielrhodes/Swift-ActionCableClient/issues/43

**Comment by ahbou** [comment]
Hey allaire 
Thanks for the heads up 👍 
I'll have some free time over the weekend to make a pull request with a fix if no one does.
Could be a good opportunity to drop JSONSerializer and adopt JSONDecoder.

**Comment by allaire** [comment]
@ahbou Sure thing go ahead, I really like how the JS client kept things simple, we could draw some inspirations from them: https://github.com/rails/rails/blob/master/actioncable/app/assets/javascripts/action_cable/subscription.coffee

**Comment by allaire** [comment]
Hi everyone,

I'm still pinned to commit `0db1c05` (which is the commit prior to this one).

Should we rollback or is there a fix planned? cc @ahbou @danielrhodes 
Thanks!

**Comment by ahbou** [comment]
Hi @allaire 
I made some progress implementing the ID the way the JS client does but not enough to open a PR.

**Pull request merged**
